name: Bug Report
description: Report a bug in Agent Core
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug in Agent Core!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this behavior?
      placeholder: |
        1. Run `agent-init "topic"`
        2. Run `agent-log ...`
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Which component?
      options:
        - init_session.py (agent-init)
        - log_url.py (agent-log)
        - sync_environments.py (agent-sync)
        - archive_session.py (agent-archive)
        - setup.sh
        - Workflows
        - Other
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - CLI (Terminal)
        - Antigravity (VSCode OSS)
        - Claude Code
        - Other
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python Version
      placeholder: "3.11"

  - type: textarea
    id: logs
    attributes:
      label: Error Output
      description: Any error messages or logs
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information
