name: Feature Request
description: Suggest a new feature for Agent Core
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature for Agent Core!

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: One sentence describing the feature
      placeholder: I want to be able to...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve?
      placeholder: Currently, I can't...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work?
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      options:
        - Session Management
        - URL Logging
        - Environment Sync
        - Memory System
        - Workflows
        - New Script
        - Integration
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Nice to have
        - Important
        - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other solutions you've thought of

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to help implement this feature
